(********************************************************************
 * COPYRIGHT --  B&R Industrial Automation GmbH 
 ********************************************************************
 * Task: AlarmX
 * Author: kay3a 
 * Created: October 3, 2024/2:53 PM 
 ********************************************************************
 * Description: Belirlenen kosullar sonrasinda AutoExport komutu olusturur.
 ********************************************************************)
ACTION AutoExport: 
		
	//|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯		
	//|               AutoExport Genarate		
	//|_________________________________________________________________________
	// belirli tarihlerde veya belirli sayiya ulasildiginda Auto Export yapilabilir.	
	Loc.Cmd.AutoExport;
	//|_________________________________________________________________________
	
END_ACTION
